<a href="https://colab.research.google.com/github/TrombBone/TelecomLabs/blob/main/Lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Упражнение 7.1**

В блокноте для этой главы, chap07.ipynb, представлены дополнительные примеры и пояснения. Прочитать блокнот и запустите код.

# **Упражнение 7.2**

Реализуйте алгоритм Быстрого Преобразования Фурье (БПФ), согласно лемме Дэниелсона-Ланцоша - рекурсивный алгоритм ДПФ. Подробности преобразований, алгоритм и самма лемма представлены в методичке.

Произведём импорт и начнём реализовывать алгоритм:

In [1]:
import numpy as np
PI2 = 2 * np.pi

In [2]:
ys = [0.9,0.8,-0.7,-0.6]
hs = np.fft.fft(ys)
hs

array([0.4+0.j , 1.6-1.4j, 0. +0.j , 1.6+1.4j])

In [3]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

In [4]:
dft(ys)

array([0.4+0.0000000e+00j, 1.6-1.4000000e+00j, 0. -4.8985872e-17j,
       1.6+1.4000000e+00j])

Разделим массив на чётные и нечётные элементы:

In [5]:
ys[::2] , ys[1::2]

([0.9, -0.7], [0.8, -0.6])

In [6]:
def my_fft(ys):
  He = dft(ys[::2])
  Ho = dft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

Не рекурсивный метод:

In [7]:
my_fft(ys)

array([0.4+0.0000000e+00j, 1.6-1.4000000e+00j, 0. -2.4492936e-17j,
       1.6+1.4000000e+00j])

In [12]:
def my_fft(ys):
  if len(ys) == 1:
    return ys
  He = my_fft(ys[::2])
  Ho = my_fft(ys[1::2])
  ns = np.arange(len(ys))
  W = np.exp(-1j * PI2 * ns / len(ys))
  return np.tile(He, 2) + W * np.tile(Ho, 2)

Рекурсивный метод:

In [13]:
my_fft(ys)

array([0.4+0.0000000e+00j, 1.6-1.4000000e+00j, 0. -2.4492936e-17j,
       1.6+1.4000000e+00j])